version: '3.1'
services:
  wmtse-data:
    image: "yoms/worst-tms-ever-data"
    volumes:
      - data:/tmp
  reverse-proxy:
    image: traefik 
    command: --api --docker 
    ports:
      - "85:80"     
      - "8085:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
  wtmse:
    image: "yoms/worst-tms-ever"
    labels:
      - "traefik.frontend.rule=PathPrefix:/sentinel2"
    environment: 
      - WTMSE_PEPSSENTINELPRODUCTDOWNLOADER_USER=worsttmsever@gmail.com
      - WTMSE_PEPSSENTINELPRODUCTDOWNLOADER_PASSWORD=RcUjCb9kJ236
    volumes: 
      - data:/tmp
  leaflet:
    image: "yoms/nginx-leaflet"
    environment: 
     - "TILESERVER=/sentinel2/{x}/{y}/{z}?zone=31TCJ&date=20180620"
    labels:
      - "traefik.frontend.rule=Path:/,/autosize.js"

volumes: 
  data: