version: '3.1'
services:
  wtmse:
    image: "yoms/worst-tms-ever"
    ports:
     - "5000:5000"
  leaflet:
    image: "yoms/nginx-leaflet"
    ports: 
     - "8080:80"
    environment: 
     - "TILESERVER=http://localhost:5000/sentinel2/{x}/{y}/{z}?zone=31TCJ&date=20180620"