version: '3.1'
services:
  reverse-proxy:
    image: traefik 
    command: --api --docker 
    ports:
      - "80:80"     
      - "8080:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
  wtmse:
    image: "yoms/worst-tms-ever"
    labels:
      - "traefik.frontend.rule=PathPrefix:/sentinel2"
  leaflet:
    image: "yoms/nginx-leaflet"
    environment: 
     - "TILESERVER=/sentinel2/{x}/{y}/{z}?zone=31TCJ&date=20180620"
    labels:
      - "traefik.frontend.rule=Path:/,/autosize.js"